# Site settings
title: Uygar KOROGLU | Blog
email: iletisim@uygarkoroglu.xyz
description: > # this means to ignore newlines until "baseurl:"
  Bir siber güvenlik meraklısının dünyası...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.uygarkoroglu.com" # the base hostname & protocol for your site
twitter_username: uygarkoroglu
github_username:  uygarkoroglu

# Build settings
markdown: kramdown
